language: c
dist: bionic

os:
- linux
- osx

compiler:
- gcc
- clang

addons:
  apt:
    packages:
    - libcairo2-dev
    - unicode-data
    - libglib2.0-dev
    - pkg-config
    - libfreetype6-dev
    - libpango1.0-dev
    - gettext
    - cmake
  homebrew:
    packages:
    - cmake
    - pkg-config
    - gettext
    - cairo
    - pango
    - fontconfig
    - freetype
    - glib
    update: true

before_script:
- '
if [ $TRAVIS_OS_NAME = osx ]; then
  export CMAKE_PREFIX_PATH="/usr/local/opt/gettext" ;
  export UNICODE_BLOCKS_ARG=-DCHECK_UNICODE_CERT=OFF ;
else
  export UNICODE_BLOCKS_ARG=-DUNICODE_BLOCKS=/usr/share/unicode/Blocks.txt ;
fi
'

script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ${UNICODE_BLOCKS_ARG} ..
- make VERBOSE=1
- ./src/fntsample --help
- make package
- tar tzf fntsample-*.tar.gz
