sudo: false
dist: xenial
language: c

compiler:
- gcc
- clang

addons:
  apt:
    packages:
    - gawk
    - libcairo2-dev
    - unicode-data
    - libglib2.0-dev
    - pkg-config
    - libfreetype6-dev
    - libpango1.0-dev
    - gettext
    - cmake

script:
- mkdir build
- cd build
- cmake .. -DCMAKE_C_FLAGS=-Werror
- make VERBOSE=1
- ./fntsample --help
- make DESTDIR=tmp install
- ls -lR tmp
