language: c
dist: bionic

os:
- linux
- osx

env:
- UNICODE_BLOCKS_ARG=-DUNICODE_BLOCKS=/usr/share/unicode/Blocks.txt
- UNICODE_BLOCKS_ARG=

compiler:
- gcc
- clang

jobs:
  exclude:
  - os: linux
    env: UNICODE_BLOCKS_ARG=
  - os: osx
    env: UNICODE_BLOCKS_ARG=-DUNICODE_BLOCKS=/usr/share/unicode/Blocks.txt

addons:
  apt:
    packages:
    - gawk
    - libcairo2-dev
    - unicode-data
    - libglib2.0-dev
    - pkg-config
    - libfreetype6-dev
    - libpango1.0-dev
    - gettext
    - cmake

before_install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cmake pkg-config gettext cairo pango fontconfig freetype glib; fi

script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ${UNICODE_BLOCKS_ARG} ..
- make VERBOSE=1
- ./src/fntsample --help
- make package
- tar tzf fntsample-*.tar.gz
