sudo: false
dist: xenial
language: c

compiler:
- gcc
- clang

addons:
  apt:
    packages:
    - gawk
    - libcairo2-dev
    - unicode-data
    - libglib2.0-dev
    - pkg-config
    - libfreetype6-dev
    - libpango1.0-dev
    - gettext
    - cmake

script:
- cmake -S . -B build -DUNICODE_BLOCKS=/usr/share/unicode/Blocks.txt
- cmake --build build -- VERBOSE=1
- cd build
- ./fntsample --help
- make DESTDIR=tmp install
- ls -lR tmp
