sudo: false
dist: xenial
language: c

compiler:
- gcc
- clang

addons:
  apt:
    packages:
    - gawk
    - libcairo2-dev
    - unicode-data
    - libglib2.0-dev
    - pkg-config
    - libfreetype6-dev
    - libpango1.0-dev
    - gettext
    - cmake

script:
- mkdir build
- cd build
- cmake -DUNICODE_BLOCKS=/usr/share/unicode/Blocks.txt ..
- make VERBOSE=1
- ./src/fntsample --help
- make package
- make DESTDIR=tmp install
- ls -lR tmp
